# Generated by Django 5.0.6 on 2024-08-05 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_remove_companyuser_company_use_user_id_763815_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False,
                 help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[
                 ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='project_created_by', to='company.companyuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='project_updated_by', to='company.companyuser')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[
                 ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=255)),
                ('permissions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Project Role',
                'verbose_name_plural': 'Project Roles',
                'db_table': 'project_roles',
                'indexes': [models.Index(fields=['name'], name='project_rol_name_4a90b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False,
                 help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False,
                 help_text='Is the user active in the project?')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('role', models.ForeignKey(help_text='Role of the user in project',
                 on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectrole')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='company.companyuser')),
            ],
            options={
                'verbose_name': 'Project User',
                'verbose_name_plural': 'Project Users',
                'db_table': 'project_users',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(
                related_name='project_users', through='project.ProjectUser', to='company.companyuser'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(
                fields=['project', 'user'], name='project_use_project_0da457_idx'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(
                fields=['role'], name='project_use_role_id_0d7a80_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company'],
                               name='projects_company_408096_idx'),
        ),
    ]
