# Generated by Django 5.0.7 on 2024-08-30 08:28

import api.v1.project.models.transcription
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(null=True, upload_to=api.v1.project.models.transcription.get_transcription_upload_to)),
                ('text', models.JSONField(default=dict, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transcription_created_by', to='project.projectuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_project', to='project.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_transcription_updated_by', to='project.projectuser')),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'db_table': 'transcriptions',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_summary_created_by', to='project.projectuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_project', to='project.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_summary_updated_by', to='project.projectuser')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.transcription')),
            ],
            options={
                'verbose_name': 'Project Summary',
                'verbose_name_plural': 'Project Summaries',
                'db_table': 'project_summaries',
            },
        ),
        migrations.CreateModel(
            name='ProjectMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_meeting_created_by', to='project.projectuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_project', to='project.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_meeting_updated_by', to='project.projectuser')),
            ],
            options={
                'verbose_name': 'Project Meeting',
                'verbose_name_plural': 'Project Meetings',
                'db_table': 'project_meetings',
                'indexes': [models.Index(fields=['project'], name='project_mee_project_1b44f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['created_by'], name='transcripti_created_65f6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['project'], name='transcripti_project_529fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['transcription'], name='project_sum_transcr_e31ece_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['created_by'], name='project_sum_created_21f9be_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['project'], name='project_sum_project_2e08b0_idx'),
        ),
    ]
