# Generated by Django 5.0.7 on 2024-09-03 10:25

import api.v1.project.models.transcription
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_transcription_summary_projectmeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='audio',
            field=models.FileField(max_length=500, null=True, upload_to=api.v1.project.models.transcription.get_transcription_upload_to),
        ),
    ]
