# Generated by Django 5.0.7 on 2024-09-12 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_transcription_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the object was created', verbose_name='Created date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the object was updated', verbose_name='Updated date time'),
            preserve_default=False,
        ),
    ]
