# Generated by Django 5.0.7 on 2024-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectrole_created_at_projectrole_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
