# Generated by Django 5.0.7 on 2024-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_summary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10, null=True),
        ),
    ]
