# Generated by Django 5.0.6 on 2024-07-25 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='What describes you the best?')),
                ('interests', models.JSONField(default=list, verbose_name='What interests you the most?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Onboarding',
                'verbose_name_plural': 'User Onboardings',
                'db_table': 'user_onboarding',
                'indexes': [models.Index(fields=['user'], name='user_onboar_user_id_c79576_idx')],
            },
        ),
    ]
