# Generated by Django 5.0.7 on 2024-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useronboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('user', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(choices=[('CREATE_TRANSCRIPTION', 'Create Transcription'), ('UPDATE_TRANSCRIPTION', 'Update Transcription'), ('DELETE_TRANSCRIPTION', 'Delete Transcription')], max_length=255)),
                ('extra_fields', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
            },
        ),
    ]
