# Generated by Django 5.0.6 on 2024-09-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="task",
            field=models.CharField(
                choices=[
                    ("CREATE_TRANSCRIPTION", "Create Transcription"),
                    ("UPDATE_TRANSCRIPTION", "Update Transcription"),
                    ("DELETE_TRANSCRIPTION", "Delete Transcription"),
                    ("CREATE_SUMMARY", "Create Summary"),
                    ("UPDATE_SUMMARY ", "Update  Summary"),
                    ("DELETE_SUMMARY ", "Delete  Summary"),
                ],
                max_length=255,
            ),
        ),
    ]
