# Generated by Django 5.0.7 on 2024-11-08 06:51

import api.v1.user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.v1.user.models.user.profile_picture_directory_path),
        ),
    ]
