# Generated by Django 5.0.7 on 2024-11-08 09:25

import api.v1.user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=api.v1.user.models.user.profile_picture_directory_path),
        ),
    ]
