# Generated by Django 5.0.6 on 2024-07-16 16:06

import django.db.models.deletion
import utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(verbose_name='Company Description')),
                ('website', models.URLField(max_length=255, verbose_name='Company Website')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=15)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(default=utils.generate_token, max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Is the user admin of the company?')),
                ('is_active', models.BooleanField(default=False, help_text='Is the user active in the company?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'db_table': 'company_users',
            },
        ),
    ]
