# Generated by Django 5.0.6 on 2024-07-24 08:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True,
                 help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False,
                 help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('ROLE_COMPANY_ADMIN', 'Company Admin'), (
                    'ROLE_MANAGER', 'Project Manager'), ('ROLE_MEMBER', 'Member')], max_length=255)),
                ('permissions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Company Role',
                'verbose_name_plural': 'Company Roles',
                'db_table': 'company_roles',
                'indexes': [models.Index(fields=['name'], name='company_rol_name_8fc3eb_idx')],
            },
        ),
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(help_text='Role of the user in company',
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='company.companyrole'),
            preserve_default=False,
        ),
    ]
