# Generated by Django 5.0.6 on 2024-08-05 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyrole_companyuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyuser',
            name='company_use_user_id_763815_idx',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(
                through='company.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='name',
            field=models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), (
                'MANAGER', 'Project Manager'), ('MEMBER', 'Member')], max_length=255),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(
                fields=['user', 'company'], name='company_use_user_id_132015_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(
                fields=['role', 'token'], name='company_use_role_id_9abdb6_idx'),
        ),
    ]
