# Generated by Django 5.0.7 on 2024-09-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companyuser_company_use_user_id_763815_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was updated', verbose_name='Updated date time')),
                ('is_deleted', models.BooleanField(default=False, help_text='Represents if a record is soft deleted', verbose_name='is record deleted')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('transcription_minutes', models.FloatField(default=0, help_text='Number of minutes transcripted in the month')),
                ('summaries_count', models.IntegerField(default=0, help_text='Number of summaries created in the month')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Company monthly usage',
                'verbose_name_plural': 'Company monthly usages',
                'db_table': 'company_monthly_usage',
                'indexes': [models.Index(fields=['month', 'year'], name='company_mon_month_52cf22_idx'), models.Index(fields=['company'], name='company_mon_company_98f365_idx')],
            },
        ),
    ]
