# Generated by Django 5.0.7 on 2024-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companymonthlyusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymonthlyusage',
            name='transcription_minutes',
        ),
        migrations.AddField(
            model_name='companymonthlyusage',
            name='transcription_duration',
            field=models.FloatField(default=0, help_text='Number of Seconds transcripted in the month'),
        ),
    ]
